#ifndef LEAFEPFRENDER_GLOBAL_H
#define LEAFEPFRENDER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LEAFEPFRENDER_LIBRARY)
#  define LEAFEPFRENDERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LEAFEPFRENDERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LEAFEPFRENDER_GLOBAL_H
